import {
  Activity,
  Baby,
  Bandage,
  Bone,
  Brain,
  ClipboardList,
  Droplet,
  Ear,
  Eye,
  FlaskConical,
  Gavel,
  Hand,
  Heart,
  Hospital,
  Microscope,
  Pill,
  Radiation,
  Scan,
  ShieldAlert,
  ShieldOff,
  ShieldPlus,
  Stethoscope,
  Syringe,
  TestTube,
  Users,
} from "lucide-react";

import { MedicalSpecialty } from "./medical-specialty";

export const specialtyIcon: Record<MedicalSpecialty, React.ElementType> = {
  [MedicalSpecialty.ALERGOLOGIA]: Droplet,
  [MedicalSpecialty.ANESTESIOLOGIA]: Syringe,
  [MedicalSpecialty.ANGIOLOGIA]: Heart,
  [MedicalSpecialty.CANCEROLOGIA]: Radiation,
  [MedicalSpecialty.CARDIOLOGIA]: Heart,
  [MedicalSpecialty.CIRURGIA_CARDIOVASCULAR]: Heart,
  [MedicalSpecialty.CIRURGIA_CABECA_PESCOCO]: Activity,
  [MedicalSpecialty.CIRURGIA_DIGESTIVA]: FlaskConical,
  [MedicalSpecialty.CIRURGIA_GERAL]: Activity,
  [MedicalSpecialty.CIRURGIA_PEDIATRICA]: Baby,
  [MedicalSpecialty.CIRURGIA_PLASTICA]: Bandage,
  [MedicalSpecialty.CIRURGIA_TORACICA]: ShieldOff,
  [MedicalSpecialty.CIRURGIA_VASCULAR]: Heart,
  [MedicalSpecialty.CLINICA_MEDICA]: Stethoscope,
  [MedicalSpecialty.DERMATOLOGIA]: Hand,
  [MedicalSpecialty.ENDOCRINOLOGIA]: FlaskConical,
  [MedicalSpecialty.ENDOSCOPIA]: Microscope,
  [MedicalSpecialty.GASTROENTEROLOGIA]: FlaskConical,
  [MedicalSpecialty.GERIATRIA]: Users,
  [MedicalSpecialty.GINECOLOGIA_OBSTETRICIA]: Baby,
  [MedicalSpecialty.HEMATOLOGIA]: Droplet,
  [MedicalSpecialty.HEPATOLOGIA]: FlaskConical,
  [MedicalSpecialty.HOMEOPATIA]: Pill,
  [MedicalSpecialty.INFECTOLOGIA]: Syringe,
  [MedicalSpecialty.MASTOLOGIA]: Stethoscope,
  [MedicalSpecialty.MEDICINA_DE_EMERGENCIA]: ShieldPlus,
  [MedicalSpecialty.MEDICINA_DO_ESPORTO]: Activity,
  [MedicalSpecialty.MEDICINA_DO_TRABALHO]: ClipboardList,
  [MedicalSpecialty.MEDICINA_DE_FAMILIA]: Users,
  [MedicalSpecialty.MEDICINA_FISICA_REABILITACAO]: Activity,
  [MedicalSpecialty.MEDICINA_INTENSIVA]: Hospital,
  [MedicalSpecialty.MEDICINA_LEGAL]: Gavel,
  [MedicalSpecialty.NEFROLOGIA]: FlaskConical,
  [MedicalSpecialty.NEUROCIRURGIA]: Brain,
  [MedicalSpecialty.NEUROLOGIA]: Brain,
  [MedicalSpecialty.NUTROLOGIA]: Pill,
  [MedicalSpecialty.OFTALMOLOGIA]: Eye,
  [MedicalSpecialty.ONCOLOGIA_CLINICA]: Radiation,
  [MedicalSpecialty.ORTOPEDIA_TRAUMATOLOGIA]: Bone,
  [MedicalSpecialty.OTORRINOLARINGOLOGIA]: Ear,
  [MedicalSpecialty.PATOLOGIA]: Microscope,
  [MedicalSpecialty.PATOLOGIA_CLINICA]: Microscope,
  [MedicalSpecialty.PEDIATRIA]: Baby,
  [MedicalSpecialty.PNEUMOLOGIA]: ShieldAlert,
  [MedicalSpecialty.PSIQUIATRIA]: Brain,
  [MedicalSpecialty.RADIOLOGIA]: Scan,
  [MedicalSpecialty.RADIOTERAPIA]: Radiation,
  [MedicalSpecialty.REUMATOLOGIA]: Bone,
  [MedicalSpecialty.UROLOGIA]: TestTube,
};

export const SpecialtyIcons = (specialty: string) => {
  const match = Object.values(MedicalSpecialty).find(
    (value) => value === specialty,
  );
  return match ? specialtyIcon[match as MedicalSpecialty] : Stethoscope;
};
